apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: horovod-hello
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: tpo-docker.ubitus.net/horovod:latest
        name: horovod
        resources:
          limits:
            nvidia.com/gpu: 1